[preprocessor]
skip_factor = 2 # Optional: skip half the input video frame (default: 2)
num_workers = 4 # Optional: thread used (default: available logical core)
queue_capacity = 32 # Optional: internal decoded queue capacity (default: 32)
min_observation = 5 # Optional: number of frame a tag must appear to be consider valid (default: 5)
max_hamming = 1 # Option: error tolerance

# Recording camera intrinsic
fx = 450.0
fy = 450.0
cx = 704.0
cy = 704.0

[streaming]
profile = "profile12" # Streaming profile (need rgb camera)
ip = "10.69.83.218" # Glasses ip available in aria app

# Streaming camera intrinsic
fx = 450.0
fy = 450.0
cx = 704.0
cy = 704.0

[apritag]
tag_family = "tag36h11"
tag_size_m = 0.05 # Tag size in meter
